// Pure vault → Claude Code plugin transform.
//
// Model: a "scope" is an agent that OWNS a set of skills. The exporter compiles a
// Johnny Decimal vault into a wired cascade:
//
//   00 general vault agent  →  area agents  →  category agents
//
//   - each agent preloads the skills in its scope via the `skills:` frontmatter field
//   - delegation is auto-wired from JD structure (root→areas, area→categories) and
//     merged with any manual `delegates-to`
//   - universal (00) skills are owned by the root vault agent; area/category skills by
//     their area/category agent
//
// No `obsidian`/`fs` imports: unit-testable under plain Node. Obsidian glue lives in
// exporter.ts.

export type Kind = "skill" | "agent";
export type Scope = "universal" | "area" | "category";

export interface NoteInput {
  /** Vault-relative path, POSIX separators. */
  path: string;
  frontmatter: Record<string, unknown>;
  /** Markdown body with frontmatter stripped. */
  body: string;
}

export interface Generated {
  kind: Kind;
  relOut: string;
  content: string;
  from: string;
}

export interface TransformOptions {
  /** Plugin name, used to namespace preloaded skill references (e.g. "vault-skills"). */
  pluginName: string;
  /** Synthesize a default root vault agent if the vault has none. Default true. */
  synthesizeRoot?: boolean;
}

export interface TransformResult {
  generated: Generated[];
  warnings: string[];
}

interface Area { code: string; range: string; name: string; }
interface Category { code: string; name: string; }

interface Rec {
  kind: Kind;
  scope: Scope;
  areaCode: string | null;
  categoryCode: string | null;
  areaName: string | null;
  categoryName: string | null;
  name: string;
  base: string;
  description: string;
  version?: string;
  tools?: string[];
  model?: string;
  body: string;
  manualDelegates: string[];
  from: string;
  // filled during wiring (agents only):
  ownedSkills: string[];
  autoDelegates: string[];
}

const str = (v: unknown): string | undefined => (typeof v === "string" ? v : undefined);

function toolsArray(v: unknown): string[] | undefined {
  if (Array.isArray(v)) return v.map(String);
  if (typeof v === "string" && v.trim()) return v.split(",").map((s) => s.trim()).filter(Boolean);
  return undefined;
}

function delegateArray(v: unknown): string[] {
  if (Array.isArray(v)) return v.map(String);
  if (typeof v === "string" && v.trim()) return [v];
  return [];
}

export function slug(s: string): string {
  return String(s).toLowerCase().trim()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function deriveFromPath(relPath: string): { area: Area | null; category: Category | null } {
  const folders = relPath.split("/").filter(Boolean).slice(0, -1);
  let area: Area | null = null;
  let category: Category | null = null;
  for (const seg of folders) {
    const am = seg.match(/^(\d{2})-(\d{2})\s+(.+)$/);
    if (am && !area) { area = { code: am[1], range: `${am[1]}-${am[2]}`, name: am[3].trim() }; continue; }
    const cm = seg.match(/^(\d{2})(?:\.\d+)?\s+(.+)$/);
    if (cm && area && !category) { category = { code: cm[1], name: cm[2].trim() }; }
  }
  return { area, category };
}

export function resolveScope(fm: Record<string, unknown>, area: Area | null, category: Category | null): Scope {
  const explicit = fm.scope;
  if (explicit === "universal" || explicit === "area" || explicit === "category") return explicit;
  if (area && area.range === "00-09") return "universal";
  if (category && category.code !== area?.code) return "category";
  if (area) return "area";
  return "universal";
}

/** Minimal YAML serializer. Quotes non-plain scalars; colon-bearing arrays become block lists. */
export function toYaml(obj: Record<string, unknown>): string {
  const out = ["---"];
  for (const [k, v] of Object.entries(obj)) {
    if (v == null || v === "" || (Array.isArray(v) && v.length === 0)) continue;
    if (Array.isArray(v)) {
      const items = v.map(String);
      if (items.some((e) => /[:#]/.test(e))) {
        out.push(`${k}:`);
        for (const e of items) out.push(`  - ${/[:#"'\n]/.test(e) ? JSON.stringify(e) : e}`);
      } else {
        out.push(`${k}: [${items.join(", ")}]`);
      }
    } else if (typeof v === "string") {
      const plain = /^[A-Za-z0-9][\w .,/()&-]*$/.test(v);
      out.push(`${k}: ${plain ? v : JSON.stringify(v)}`);
    } else out.push(`${k}: ${String(v)}`);
  }
  out.push("---");
  return out.join("\n");
}

function provenanceFor(from: string): string {
  return `<!-- generated by obsidian-vault-skills from vault note: ${from}\n     Do not edit here — edit the source note and re-export. -->`;
}

function scopeLabel(r: Rec): string {
  if (r.scope === "universal") return r.areaName ?? "vault";
  if (r.scope === "area") return r.areaName ?? "area";
  return r.categoryName ?? "category";
}

function synthRoot(): Rec {
  return {
    kind: "agent", scope: "universal", areaCode: "00", categoryCode: null,
    areaName: "Vault", categoryName: null,
    name: "00-vault", base: "vault",
    description: "[Vault] General vault agent — routes a request to the appropriate area agent, which routes on to category agents.",
    body: "You are the general agent for this vault. Understand each request, identify which Johnny Decimal area it belongs to, and delegate to that area's agent. For cross-area requests, coordinate across areas yourself.",
    tools: ["Agent"],
    manualDelegates: [], from: "(synthesized)", ownedSkills: [], autoDelegates: [],
  };
}

export function transformAll(notes: NoteInput[], opts: TransformOptions): TransformResult {
  const warnings: string[] = [];
  const usedNames = new Set<string>();
  const records: Rec[] = [];

  // ---- phase 1: parse every note into a record ----
  for (const note of notes) {
    const fm = note.frontmatter || {};
    const kind: Kind | null = fm.type === "agent" ? "agent" : fm.type === "skill" ? "skill" : null;
    if (!kind) continue;

    const { area, category } = deriveFromPath(note.path);
    const scope = resolveScope(fm, area, category);
    const id = String(
      str(fm.id) ??
      (scope === "universal" ? "00" : scope === "category" ? category?.code : area?.code) ?? "00",
    );
    const breadcrumb = scope === "universal" ? (area ? area.name : "Universal")
      : scope === "area" ? (area ? area.name : "Area")
      : `${area ? area.name : "Area"} › ${category ? category.name : ""}`;

    const fileBase = (note.path.split("/").pop() ?? "").replace(/\.md$/, "");
    const base = slug(str(fm.name) || fileBase);
    let name = `${id}-${base}`;
    let n = 2;
    while (usedNames.has(name)) name = `${id}-${base}-${n++}`;
    usedNames.add(name);

    const rawDesc = String(str(fm.description) || base.replace(/-/g, " ")).trim();
    records.push({
      kind, scope,
      areaCode: area?.code ?? null,
      categoryCode: scope === "category" ? (category?.code ?? null) : null,
      areaName: area?.name ?? null,
      categoryName: category?.name ?? null,
      name, base,
      description: `[${breadcrumb}] ${rawDesc}`,
      version: str(fm.version), tools: toolsArray(fm.tools), model: str(fm.model),
      body: note.body.trim(),
      manualDelegates: delegateArray(fm["delegates-to"]),
      from: note.path,
      ownedSkills: [], autoDelegates: [],
    });
  }

  // ---- phase 2: wire the cascade ----
  const universalAgents = records.filter((r) => r.kind === "agent" && r.scope === "universal");
  let root: Rec | null = universalAgents[0] ?? null;
  if (universalAgents.length > 1) warnings.push(`multiple universal agents; using "${root!.name}" as the vault root`);
  if (!root && opts.synthesizeRoot !== false) {
    root = synthRoot();
    records.unshift(root);
    usedNames.add(root.name);
  }

  const areaAgents = new Map<string, Rec>();
  const categoryAgentsByArea = new Map<string, Rec[]>();
  for (const r of records) {
    if (r.kind !== "agent") continue;
    if (r.scope === "area" && r.areaCode) {
      if (areaAgents.has(r.areaCode)) warnings.push(`multiple area agents for ${r.areaCode}; using "${areaAgents.get(r.areaCode)!.name}"`);
      else areaAgents.set(r.areaCode, r);
    } else if (r.scope === "category" && r.areaCode) {
      const arr = categoryAgentsByArea.get(r.areaCode) ?? [];
      arr.push(r);
      categoryAgentsByArea.set(r.areaCode, arr);
    }
  }

  // skill ownership by scope
  for (const r of records) {
    if (r.kind !== "skill") continue;
    let owner: Rec | null = null;
    if (r.scope === "universal") owner = root;
    else if (r.scope === "area" && r.areaCode) owner = areaAgents.get(r.areaCode) ?? null;
    else if (r.scope === "category" && r.areaCode) {
      owner = (categoryAgentsByArea.get(r.areaCode) ?? []).find((a) => a.categoryCode === r.categoryCode) ?? null;
    }
    if (owner) owner.ownedSkills.push(r.name);
    else warnings.push(`skill "${r.name}" has no owning agent (emitted globally, unowned)`);
  }

  // delegation: root → all area agents; each area agent → its category agents
  if (root) root.autoDelegates = [...areaAgents.values()].map((a) => a.name);
  for (const [areaCode, agent] of areaAgents) {
    agent.autoDelegates = (categoryAgentsByArea.get(areaCode) ?? []).map((a) => a.name);
  }

  const agentByBase = new Map<string, string>();
  for (const r of records) if (r.kind === "agent") agentByBase.set(r.base, r.name);
  const resolveManual = (d: string): string | null => {
    const target = d.replace(/\[\[|\]\]/g, "").split("|")[0].trim();
    return agentByBase.get(slug(target)) ?? null;
  };
  const nameToRec = new Map(records.map((r) => [r.name, r]));

  // ---- phase 3: render ----
  const generated: Generated[] = [];
  for (const r of records) {
    if (r.kind === "skill") {
      const fmOut = toYaml({ name: r.name, description: r.description, version: r.version });
      generated.push({
        kind: "skill", relOut: `skills/${r.name}/SKILL.md`, from: r.from,
        content: `${fmOut}\n\n${provenanceFor(r.from)}\n\n${r.body}\n`,
      });
      continue;
    }

    // agent: merge auto + manual delegates
    const manual = r.manualDelegates.map((d) => {
      const g = resolveManual(d);
      if (!g) warnings.push(`${r.name}: unresolved delegate ${d}`);
      return g;
    }).filter((g): g is string => !!g);
    const delegates = [...new Set([...r.autoDelegates, ...manual])];

    let tools = r.tools;
    if (delegates.length && tools && !tools.includes("Agent")) tools = [...tools, "Agent"];

    const skillRefs = r.ownedSkills.map((n) => `${opts.pluginName}:${n}`);
    const fmOut = toYaml({ name: r.name, description: r.description, tools, model: r.model, skills: skillRefs });

    let bodyOut = r.body;
    if (skillRefs.length) {
      bodyOut += `\n\n## Skills\n\nThese scope skills are preloaded into your context — use them for work in this scope: ${skillRefs.map((s) => `\`${s}\``).join(", ")}.`;
    }
    if (delegates.length) {
      const items = delegates.map((dn) => {
        const dr = nameToRec.get(dn);
        return dr ? `- \`${dn}\` — ${scopeLabel(dr)}` : `- \`${dn}\``;
      });
      const heading = r.scope === "universal"
        ? "## Vault routing\n\nYou are the general vault agent. Identify which area a request belongs to and delegate to that area's agent via the Agent tool (nested subagents work up to 5 levels deep):"
        : r.scope === "area"
          ? "## Delegates to\n\nDelegate category-specific work to the matching category agent via the Agent tool:"
          : "## Delegates to\n\nSpawn the named agent via the Agent tool for that sub-scope:";
      bodyOut += `\n\n${heading}\n${items.join("\n")}`;
    }

    generated.push({
      kind: "agent", relOut: `agents/${r.name}.md`, from: r.from,
      content: `${fmOut}\n\n${provenanceFor(r.from)}\n\n${bodyOut}\n`,
    });
  }

  return { generated, warnings };
}
