// Pure vault → Claude Code plugin transform (frontmatter tree model).
//
// A note declares `type` (skill|agent) and a single `parent` ([[wikilink]], resolved to a
// path by the caller). The exporter builds a strict tree, validates its edges, and compiles
// it: each agent owns the skills whose parent is it (preloaded via `skills:`) and delegates
// to the agents whose parent is it. See docs/spec-frontmatter-tree.md.
//
// No `obsidian`/`fs` imports — unit-testable. Parent wikilinks are resolved to note paths by
// exporter.ts (Obsidian); this module works purely on those paths.

export type Kind = "skill" | "agent";

export interface NoteInput {
  path: string;
  frontmatter: Record<string, unknown>;
  body: string;
  /** Resolved parent note path(s). 0 ⇒ child of root; 1 ⇒ that parent; >1 ⇒ error. */
  parentPaths: string[];
}

export interface Generated {
  kind: Kind;
  relOut: string;
  content: string;
  from: string;
}

export interface TransformOptions {
  pluginName: string;
  synthesizeRoot?: boolean;
  /** Absolute vault path, baked into each agent so it can read/write the vault. */
  vaultPath?: string;
}

export interface TransformResult {
  generated: Generated[];
  warnings: string[];
  errors: string[];
}

interface Node {
  kind: Kind;
  path: string;
  isRoot: boolean;
  parentPaths: string[];
  nameBase: string;
  id?: string;
  label: string;
  rawDesc: string;
  version?: string;
  tools?: string[];
  model?: string;
  body: string;
  // resolved:
  parent: Node | null;
  children: Node[];
  ownedSkills: Node[];
  level: number;
  genName: string;
  valid: boolean;
}

const SYNTH_ROOT_PATH = " synth-root";

const str = (v: unknown): string | undefined => (typeof v === "string" ? v : undefined);

function toolsArray(v: unknown): string[] | undefined {
  if (Array.isArray(v)) return v.map(String);
  if (typeof v === "string" && v.trim()) return v.split(",").map((s) => s.trim()).filter(Boolean);
  return undefined;
}

export function slug(s: string): string {
  return String(s).toLowerCase().trim()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function toYaml(obj: Record<string, unknown>): string {
  const out = ["---"];
  for (const [k, v] of Object.entries(obj)) {
    if (v == null || v === "" || (Array.isArray(v) && v.length === 0)) continue;
    if (Array.isArray(v)) {
      const items = v.map(String);
      if (items.some((e) => /[:#]/.test(e))) {
        out.push(`${k}:`);
        for (const e of items) out.push(`  - ${/[:#"'\n]/.test(e) ? JSON.stringify(e) : e}`);
      } else {
        out.push(`${k}: [${items.join(", ")}]`);
      }
    } else if (typeof v === "string") {
      const plain = /^[A-Za-z0-9][\w .,/()&-]*$/.test(v);
      out.push(`${k}: ${plain ? v : JSON.stringify(v)}`);
    } else out.push(`${k}: ${String(v)}`);
  }
  out.push("---");
  return out.join("\n");
}

function provenanceFor(from: string): string {
  return `<!-- generated by obsidian-vault-skills from vault note: ${from}\n     Do not edit here — edit the source note and re-export. -->`;
}

function fileBaseOf(path: string): string {
  return (path.split("/").pop() ?? "").replace(/\.md$/, "");
}

export function transformAll(notes: NoteInput[], opts: TransformOptions): TransformResult {
  const warnings: string[] = [];
  const errors: string[] = [];

  // ---- phase 1: parse candidate nodes ----
  const nodes: Node[] = [];
  for (const note of notes) {
    const fm = note.frontmatter || {};
    const kind: Kind | null = fm.type === "agent" ? "agent" : fm.type === "skill" ? "skill" : null;
    if (!kind) continue;
    const fileBase = fileBaseOf(note.path);
    nodes.push({
      kind,
      path: note.path,
      isRoot: fm.root === true,
      parentPaths: note.parentPaths ?? [],
      nameBase: slug(str(fm.name) || fileBase),
      id: str(fm.id),
      label: str(fm.label) || str(fm.name) || fileBase,
      rawDesc: String(str(fm.description) || slug(str(fm.name) || fileBase).replace(/-/g, " ")).trim(),
      version: str(fm.version),
      tools: toolsArray(fm.tools),
      model: str(fm.model),
      body: note.body.trim(),
      parent: null, children: [], ownedSkills: [], level: -1, genName: "", valid: true,
    });
  }
  const byPath = new Map(nodes.map((n) => [n.path, n]));

  // ---- phase 2: root ----
  const declaredRoots = nodes.filter((n) => n.isRoot);
  for (const r of declaredRoots) {
    if (r.kind !== "agent") { r.valid = false; errors.push(`${r.path}: root must be an agent`); }
  }
  const validRoots = declaredRoots.filter((r) => r.valid);
  for (const extra of validRoots.slice(1)) { extra.valid = false; errors.push(`${extra.path}: multiple roots; ignoring this one`); }
  let root: Node | null = validRoots[0] ?? null;
  if (!root && opts.synthesizeRoot !== false) {
    root = {
      kind: "agent", path: SYNTH_ROOT_PATH, isRoot: true, parentPaths: [],
      nameBase: "vault", label: "Vault",
      rawDesc: "General vault agent — routes each request to the appropriate sub-agent.",
      body: "You are the general agent for this vault. Understand each request and delegate to the appropriate sub-agent; coordinate across sub-agents yourself when a request spans several.",
      parent: null, children: [], ownedSkills: [], level: 0, genName: "", valid: true,
    };
    nodes.unshift(root);
    byPath.set(root.path, root);
  }
  if (root) root.level = 0;

  // ---- phase 3: resolve each node's parent ----
  for (const n of nodes) {
    if (n === root) continue;
    if (n.parentPaths.length > 1) { n.valid = false; errors.push(`${n.path}: multiple parents (strict single-parent)`); continue; }
    if (n.parentPaths.length === 0) {
      if (!root) { n.valid = false; errors.push(`${n.path}: no parent and no root`); continue; }
      n.parent = root; continue;
    }
    const parent = byPath.get(n.parentPaths[0]);
    if (!parent) { n.valid = false; errors.push(`${n.path}: unresolved parent ${n.parentPaths[0]}`); continue; }
    if (parent.kind !== "agent") { n.valid = false; errors.push(`${n.path}: parent is not an agent`); continue; }
    n.parent = parent;
  }

  // ---- phase 4: validate reachability / cycles / depth; compute level ----
  for (const n of nodes) {
    if (!n.valid || n === root) continue;
    const seen = new Set<string>([n.path]);
    let cur: Node | null = n.parent;
    let steps = 1;
    while (cur && !cur.isRoot) {
      if (seen.has(cur.path) || !cur.valid) { n.valid = false; break; }
      seen.add(cur.path);
      cur = cur.parent;
      steps++;
    }
    if (!n.valid) { errors.push(`${n.path}: broken parent chain (cycle or invalid ancestor)`); continue; }
    if (!cur) { n.valid = false; errors.push(`${n.path}: parent chain does not reach the root`); continue; }
    n.level = steps;
    if (n.kind === "agent" && n.level > 4) warnings.push(`${n.path}: agent at level ${n.level} exceeds the depth-5 nesting cap and won't be reachable by live delegation`);
  }

  // ---- phase 5: wire children + ownership from valid nodes ----
  for (const n of nodes) {
    if (!n.valid || n === root || !n.parent) continue;
    if (n.kind === "agent") n.parent.children.push(n);
    else n.parent.ownedSkills.push(n);
  }

  // ---- phase 6: names (dedup) ----
  const used = new Set<string>();
  for (const n of nodes) {
    if (!n.valid) continue;
    const base = n.id ? `${n.id}-${n.nameBase}` : n.nameBase;
    let name = base; let k = 2;
    while (used.has(name)) name = `${base}-${k++}`;
    used.add(name);
    n.genName = name;
  }

  const breadcrumb = (n: Node): string => {
    const labels: string[] = [];
    let cur = n.parent;
    while (cur && !cur.isRoot) { labels.unshift(cur.label); cur = cur.parent; }
    return labels.join(" › ");
  };
  const describe = (n: Node): string => {
    const bc = breadcrumb(n);
    return bc ? `[${bc}] ${n.rawDesc}` : n.rawDesc;
  };

  // ---- phase 7: render ----
  const generated: Generated[] = [];
  for (const n of nodes) {
    if (!n.valid) continue;

    if (n.kind === "skill") {
      const fmOut = toYaml({ name: n.genName, description: describe(n), version: n.version });
      generated.push({ kind: "skill", relOut: `skills/${n.genName}/SKILL.md`, from: n.path,
        content: `${fmOut}\n\n${provenanceFor(n.path)}\n\n${n.body}\n` });
      continue;
    }

    // agent — guarantee structural tools from tree position (Agent to delegate, Skill to
    // invoke owned skills). Only matters when tools are explicitly listed; omitting tools
    // inherits everything.
    let tools = n.tools;
    if (n.children.length && tools && !tools.includes("Agent")) tools = [...tools, "Agent"];
    if (n.ownedSkills.length && tools && !tools.includes("Skill")) tools = [...tools, "Skill"];
    const skillRefs = n.ownedSkills.map((s) => `${opts.pluginName}:${s.genName}`);
    const fmOut = toYaml({ name: n.genName, description: describe(n), tools, model: n.model, skills: skillRefs });

    let bodyOut = n.body;
    if (opts.vaultPath) {
      bodyOut += `\n\n## Vault access\n\nYour skills and agents are authored in the Obsidian vault at \`${opts.vaultPath}\`. You can read and write notes there directly (Read/Grep/Glob and Write/Edit under that path), or use the \`vault-mcp\` tools if connected.`;
    }
    if (skillRefs.length) {
      bodyOut += `\n\n## Skills\n\nThese scope skills are preloaded into your context — use them for work in this scope: ${skillRefs.map((s) => `\`${s}\``).join(", ")}.`;
    }
    if (n.children.length) {
      const items = n.children.map((c) => `- \`${c.genName}\` — ${c.label}`);
      const heading = n.isRoot
        ? "## Vault routing\n\nYou are the general vault agent. Identify which sub-agent a request belongs to and delegate to it via the Agent tool (nested subagents work up to 5 levels deep):"
        : "## Delegates to\n\nDelegate sub-scope work to the matching agent via the Agent tool:";
      bodyOut += `\n\n${heading}\n${items.join("\n")}`;
    }

    const src = n.path === SYNTH_ROOT_PATH ? "(synthesized root)" : n.path;
    generated.push({ kind: "agent", relOut: `agents/${n.genName}.md`, from: src,
      content: `${fmOut}\n\n${provenanceFor(src)}\n\n${bodyOut}\n` });
  }

  return { generated, warnings, errors };
}
