// Pure vault → Claude Code plugin transform.
//
// No `obsidian` or `fs` imports on purpose: this module is unit-testable under
// plain Node, and holds all the JD-derivation + rendering logic. The Obsidian
// glue (discovery via metadataCache, filesystem writes) lives in exporter.ts.

export type Kind = "skill" | "agent";
export type Scope = "universal" | "area" | "category";

/** One candidate note, with frontmatter already parsed (by Obsidian's cache). */
export interface NoteInput {
  /** Vault-relative path, POSIX separators. */
  path: string;
  frontmatter: Record<string, unknown>;
  /** Markdown body with frontmatter stripped. */
  body: string;
}

export interface Generated {
  kind: Kind;
  /** Output path relative to the plugin root, e.g. "skills/56-x/SKILL.md". */
  relOut: string;
  content: string;
  from: string;
}

export interface TransformResult {
  generated: Generated[];
  warnings: string[];
}

interface Area { code: string; range: string; name: string; }
interface Category { code: string; name: string; }

const str = (v: unknown): string | undefined => (typeof v === "string" ? v : undefined);

function toolsArray(v: unknown): string[] | undefined {
  if (Array.isArray(v)) return v.map(String);
  if (typeof v === "string" && v.trim()) return v.split(",").map((s) => s.trim()).filter(Boolean);
  return undefined;
}

function delegateArray(v: unknown): string[] {
  if (Array.isArray(v)) return v.map(String);
  if (typeof v === "string" && v.trim()) return [v];
  return [];
}

export function slug(s: string): string {
  return String(s).toLowerCase().trim()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Infer area + category from the Johnny Decimal folder names in the path. */
export function deriveFromPath(relPath: string): { area: Area | null; category: Category | null } {
  const folders = relPath.split("/").filter(Boolean).slice(0, -1); // drop filename
  let area: Area | null = null;
  let category: Category | null = null;
  for (const seg of folders) {
    const am = seg.match(/^(\d{2})-(\d{2})\s+(.+)$/);
    if (am && !area) { area = { code: am[1], range: `${am[1]}-${am[2]}`, name: am[3].trim() }; continue; }
    const cm = seg.match(/^(\d{2})(?:\.\d+)?\s+(.+)$/);
    if (cm && area && !category) { category = { code: cm[1], name: cm[2].trim() }; }
  }
  return { area, category };
}

export function resolveScope(fm: Record<string, unknown>, area: Area | null, category: Category | null): Scope {
  const explicit = fm.scope;
  if (explicit === "universal" || explicit === "area" || explicit === "category") return explicit;
  if (area && area.range === "00-09") return "universal";
  // The X0 "management" category represents the area itself, not a sub-category.
  if (category && category.code !== area?.code) return "category";
  if (area) return "area";
  return "universal";
}

/** Minimal YAML frontmatter serializer. Double-quotes anything not a safe plain scalar. */
export function toYaml(obj: Record<string, unknown>): string {
  const out = ["---"];
  for (const [k, v] of Object.entries(obj)) {
    if (v == null || v === "" || (Array.isArray(v) && v.length === 0)) continue;
    if (Array.isArray(v)) out.push(`${k}: [${v.join(", ")}]`);
    else if (typeof v === "string") {
      // A leading "[" (every description starts with "[breadcrumb]") would be read
      // as a flow sequence unquoted, so quote anything that isn't a plain scalar.
      const plain = /^[A-Za-z0-9][\w .,/()&-]*$/.test(v);
      out.push(`${k}: ${plain ? v : JSON.stringify(v)}`);
    } else out.push(`${k}: ${String(v)}`);
  }
  out.push("---");
  return out.join("\n");
}

function provenanceFor(from: string): string {
  return `<!-- generated by obsidian-vault-skills from vault note: ${from}\n     Do not edit here — edit the source note and re-export. -->`;
}

interface Rec {
  kind: Kind; name: string; base: string; description: string;
  version?: string; tools?: string[]; model?: string; body: string;
  delegates: string[]; from: string;
}

/** Transform a set of candidate notes into generated skill/agent files. */
export function transformAll(notes: NoteInput[]): TransformResult {
  const warnings: string[] = [];
  const usedNames = new Set<string>();
  const records: Rec[] = [];

  for (const note of notes) {
    const fm = note.frontmatter || {};
    const kind: Kind | null = fm.type === "agent" ? "agent" : fm.type === "skill" ? "skill" : null;
    if (!kind) continue;

    const { area, category } = deriveFromPath(note.path);
    const scope = resolveScope(fm, area, category);
    const id = String(
      str(fm.id) ??
      (scope === "universal" ? "00" : scope === "category" ? category?.code : area?.code) ?? "00",
    );
    const breadcrumb = scope === "universal" ? (area ? area.name : "Universal")
      : scope === "area" ? (area ? area.name : "Area")
      : `${area ? area.name : "Area"} › ${category ? category.name : ""}`;

    const fileBase = (note.path.split("/").pop() ?? "").replace(/\.md$/, "");
    const base = slug(str(fm.name) || fileBase);
    let name = `${id}-${base}`;
    let n = 2;
    while (usedNames.has(name)) name = `${id}-${base}-${n++}`;
    usedNames.add(name);

    const rawDesc = String(str(fm.description) || base.replace(/-/g, " ")).trim();
    records.push({
      kind, name, base, description: `[${breadcrumb}] ${rawDesc}`,
      version: str(fm.version), tools: toolsArray(fm.tools), model: str(fm.model),
      body: note.body.trim(),
      delegates: delegateArray(fm["delegates-to"]),
      from: note.path,
    });
  }

  // A delegate wikilink resolves to the generated name of the agent from that note.
  const agentByBase = new Map<string, string>();
  for (const r of records) if (r.kind === "agent") agentByBase.set(r.base, r.name);
  const resolveDelegate = (d: string): string | null => {
    const target = d.replace(/\[\[|\]\]/g, "").split("|")[0].trim();
    return agentByBase.get(slug(target)) ?? null;
  };

  const generated: Generated[] = [];
  for (const r of records) {
    if (r.kind === "skill") {
      const fmOut = toYaml({ name: r.name, description: r.description, version: r.version });
      generated.push({
        kind: "skill", relOut: `skills/${r.name}/SKILL.md`, from: r.from,
        content: `${fmOut}\n\n${provenanceFor(r.from)}\n\n${r.body}\n`,
      });
    } else {
      // Real delegation needs the Agent tool. If tools are listed, ensure Agent is
      // present; if omitted the agent inherits all tools (Agent included).
      let tools = r.tools;
      if (r.delegates.length && tools && !tools.includes("Agent")) tools = [...tools, "Agent"];
      const fmOut = toYaml({ name: r.name, description: r.description, tools, model: r.model });

      let bodyOut = r.body;
      if (r.delegates.length) {
        const lines = r.delegates.map((d) => {
          const gen = resolveDelegate(d);
          if (!gen) warnings.push(`${r.name}: unresolved delegate ${d}`);
          return gen
            ? `- \`${gen}\` — spawn this agent (via the Agent tool) for that sub-scope`
            : `- ${d} — unresolved: no matching agent note found`;
        });
        bodyOut += `\n\n## Delegates to\n\nWhen a request falls under one of these sub-scopes, spawn the named agent with the Agent tool and let it handle the work. Nested subagents are supported up to 5 levels below the main conversation.\n${lines.join("\n")}`;
      }
      generated.push({
        kind: "agent", relOut: `agents/${r.name}.md`, from: r.from,
        content: `${fmOut}\n\n${provenanceFor(r.from)}\n\n${bodyOut}\n`,
      });
    }
  }

  return { generated, warnings };
}
